In [56]:
import pandas as pd
import statsmodels.api as sm
import pylab as pl
import numpy as np

In [57]:
df = pd.read_csv('FFMLTESTRB.csv')
df.head()

,GAME,WEEK,Thu,Sun,Mon,AGE,DOME,OPEN_STADIUM,STADIUM_OPENED_YEAR,TURF,GRASS,PLAYER_EXP_Y,LAST_WEEK_DK_POINTS,LAST_3_WEEK_DK_POINTS,LAST_6_WEEK_DK_POINTS,OVER_12
0,4,4,1,0,0,22.300,0,1,1957,0,1,0,0.0,0.0,0.0,0
1,5,5,0,1,0,22.310,0,1,1957,0,1,0,10.9,10.9,10.9,1
2,6,6,0,1,0,22.317,1,1,1957,0,1,0,21.5,32.4,32.4,0
3,7,7,0,1,0,22.324,0,1,1957,0,1,0,4.1,36.5,36.5,1
4,14,15,0,1,0,23.015,0,1,1957,0,1,0,0.0,0.0,0.0,0

In [58]:
data = df

In [59]:
train_cols = data.columns[:-1]
logit = sm.Logit(data['OVER_12'], data[train_cols])
result = logit.fit()
print (result.summary())

Optimization terminated successfully.
         Current function value: 0.623650
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                OVER_12   No. Observations:                 1590
Model:                          Logit   Df Residuals:                     1575
Method:                           MLE   Df Model:                           14
Date:                Thu, 03 Oct 2019   Pseudo R-squ.:                 0.07541
Time:                        13:10:48   Log-Likelihood:                -991.60
converged:                       True   LL-Null:                       -1072.5
Covariance Type:            nonrobust   LLR p-value:                 3.170e-27
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
GAME                     -0.1166      0.206     -0.565      0.572      -0.521       0.288
WEEK                      0.0736      0.190      0.388      0.698      -0.298       0.446
Thu                       0.9251      0.582      1.589      0.112      -0.216       2.066
Sun                       0.9285      0.546      1.701      0.089      -0.141       1.998
Mon                       1.0465      0.580      1.803      0.071      -0.091       2.184
AGE                      -0.0767      0.036     -2.117      0.034      -0.148      -0.006
DOME                      0.3332      0.176      1.889      0.059      -0.013       0.679
OPEN_STADIUM              0.2059      0.160      1.286      0.198      -0.108       0.520
STADIUM_OPENED_YEAR      -0.0016      0.003     -0.611      0.541      -0.007       0.004
TURF                      3.2494      5.455      0.596      0.551      -7.443      13.942
GRASS                     3.2829      5.435      0.604      0.546      -7.369      13.935
PLAYER_EXP_Y              0.0172      0.042      0.414      0.679      -0.064       0.099
LAST_WEEK_DK_POINTS       0.0157      0.008      1.915      0.056      -0.000       0.032
LAST_3_WEEK_DK_POINTS     0.0070      0.006      1.125      0.261      -0.005       0.019
LAST_6_WEEK_DK_POINTS     0.0111      0.003      3.257      0.001       0.004       0.018
=========================================================================================